/**
vmlinux.h is autogenerated. Run the following comand in your machine if you want
to use it:

    bpftool btf dump file /sys/kernel/btf/vmlinux format c > user-activity_ebpf/bpf/vmlinux.h

What's vmlinux.h for?
The command generates a vmlinux.h header file with all kernel types (BTF types) that the running kernel uses.
Including vmlinux.h in your BPF program eliminates dependency on system-wide kernel headers.

For more information refer to this page:
https://docs.kernel.org/bpf/libbpf/libbpf_overview.html
*/

#include "vmlinux.h"

#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>

#define ACTION_LEN 16
#define MAX_ENTRIES 1024

struct user_action {
    u32 pid;
    u32 uid;
    char action[ACTION_LEN];
};

struct {
    __uint(type, BPF_MAP_TYPE_PERF_EVENT_ARRAY);
    __uint(max_entries, MAX_ENTRIES);
    __type(key, u32);
    __type(value, u32);
} user_actions_map SEC(".maps");

SEC("tracepoint/syscalls/sys_enter_setuid")
int trace_login(struct trace_event_raw_sys_enter *ctx)
{
    struct user_action action_info = {};
    u32 uid = (u32)ctx->id;

    // Obtain the current process PID and user name
    action_info.pid = bpf_get_current_pid_tgid() >> 32;
    action_info.uid = bpf_get_current_uid_gid();

    // Set action to "login"
    __builtin_memcpy(action_info.action, "login", sizeof("login"));

    bpf_perf_event_output(ctx, &user_actions_map, BPF_F_CURRENT_CPU, &action_info, sizeof(action_info));

    return 0;
}

SEC("tracepoint/syscalls/sys_enter_exit")
int trace_logout(struct trace_event_raw_sys_enter *ctx)
{
    struct user_action action_info = {};

    // Obtain the current process PID and user name
    action_info.pid = bpf_get_current_pid_tgid() >> 32;
    action_info.uid = bpf_get_current_uid_gid();

    // Set action to "logout"
    __builtin_memcpy(action_info.action, "logout", sizeof("logout"));

    bpf_perf_event_output(ctx, &user_actions_map, BPF_F_CURRENT_CPU, &action_info, sizeof(action_info));

    return 0;
}

char LICENSE[] SEC("license") = "GPL";