/**
vmlinux.h is autogenerated. Run the following comand in your machine if you want
to use it:

    bpftool btf dump file /sys/kernel/btf/vmlinux format c > user-activity_ebpf/bpf/vmlinux.h

What's vmlinux.h for?
The command generates a vmlinux.h header file with all kernel types (BTF types) that the running kernel uses.
Including vmlinux.h in your BPF program eliminates dependency on system-wide kernel headers.

For more information refer to this page:
https://docs.kernel.org/bpf/libbpf/libbpf_overview.html
*/

#include "vmlinux.h"

#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>

#define MAX_USER_LEN 32

struct user_action {
    u32 pid;
    char user[MAX_USER_LEN];
    char action[10];
};

struct {
    __uint(type, BPF_MAP_TYPE_PERF_EVENT_ARRAY);
} events SEC(".maps");

SEC("tracepoint/syscalls/sys_enter_setuid")
int trace_login(struct trace_event_raw_sys_enter *ctx)
{
    struct user_action event = {};
    u32 uid = (u32)ctx->id;

    // Obtain the current process PID and user name
    event.pid = bpf_get_current_pid_tgid() >> 32;
    bpf_get_current_comm(event.user, sizeof(event.user));

    // Set action to "login"
    __builtin_memcpy(event.action, "login", sizeof("login"));

    bpf_perf_event_output(ctx, &events, BPF_F_CURRENT_CPU, &event, sizeof(event));

    return 0;
}

SEC("tracepoint/syscalls/sys_enter_exit")
int trace_logout(struct trace_event_raw_sys_enter *ctx)
{
    struct user_action event = {};

    // Obtain the current process PID and user name
    event.pid = bpf_get_current_pid_tgid() >> 32;
    bpf_get_current_comm(event.user, sizeof(event.user));

    // Set action to "logout"
    __builtin_memcpy(event.action, "logout", sizeof("logout"));

    bpf_perf_event_output(ctx, &events, BPF_F_CURRENT_CPU, &event, sizeof(event));

    return 0;
}

char LICENSE[] SEC("license") = "GPL";