package main

import (
	"bytes"
	"debug/elf"
	"encoding/binary"
	"fmt"
	"log"
	"os"
	"os/signal"
	"syscall"

	"github.com/cilium/ebpf/link"
)

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -target bpfel -cc clang code code.bpf.c -- -I/usr/include/linux/bpf.h -D__TARGET_ARCH_x86

const (
	targetPath = "./target"
	provider   = "myapp"
	probeName  = "order_processed"
)

// stapsdtNote mirrors the descriptor of a single .note.stapsdt ELF note, as
// generated by sys/sdt.h's DTRACE_PROBE macros: two link-time addresses
// (Location, the probe's call site; Base, an anchor used to correct Location
// on prelinked binaries, unused here), an optional Semaphore address (0 when
// the probe defines none, as is the case in this example) and three
// NUL-separated strings describing the probe itself.
type stapsdtNote struct {
	Location  uint64
	Base      uint64
	Semaphore uint64
	Provider  string
	Probe     string
	Arg       string
}

// parseStapsdtNotes walks the raw .note.stapsdt section data. cilium/ebpf has
// no built-in USDT support, so this is the same parsing a tool like bpftrace
// or libbpf's own bpf_program__attach_usdt() would do internally.
func parseStapsdtNotes(data []byte) ([]stapsdtNote, error) {
	align := func(n int) int { return (n + 3) &^ 3 }

	var notes []stapsdtNote
	for len(data) >= 12 {
		nameSz := binary.LittleEndian.Uint32(data[0:4])
		descSz := binary.LittleEndian.Uint32(data[4:8])
		noteType := binary.LittleEndian.Uint32(data[8:12])
		data = data[12:]

		if len(data) < align(int(nameSz))+align(int(descSz)) {
			return nil, fmt.Errorf("malformed note: truncated name/descriptor")
		}

		name := string(bytes.TrimRight(data[:nameSz], "\x00"))
		data = data[align(int(nameSz)):]

		desc := data[:descSz]
		data = data[align(int(descSz)):]

		if noteType != 3 || name != "stapsdt" || len(desc) < 24 {
			continue
		}

		fields := bytes.SplitN(desc[24:], []byte{0}, 3)
		if len(fields) < 2 {
			continue
		}

		notes = append(notes, stapsdtNote{
			Location:  binary.LittleEndian.Uint64(desc[0:8]),
			Base:      binary.LittleEndian.Uint64(desc[8:16]),
			Semaphore: binary.LittleEndian.Uint64(desc[16:24]),
			Provider:  string(fields[0]),
			Probe:     string(fields[1]),
		})
	}

	return notes, nil
}

// usdtOffset resolves the file offset of a USDT probe: it finds the matching
// stapsdt note and translates its link-time Location address into a file
// offset, using the exact same PT_LOAD-segment lookup cilium/ebpf itself uses
// internally to resolve regular ELF symbols for kprobes/uprobes.
func usdtOffset(f *elf.File, provider, probe string) (uint64, error) {
	section := f.Section(".note.stapsdt")
	if section == nil {
		return 0, fmt.Errorf("no .note.stapsdt section: was the target built with a USDT probe?")
	}

	data, err := section.Data()
	if err != nil {
		return 0, fmt.Errorf("reading .note.stapsdt: %w", err)
	}

	notes, err := parseStapsdtNotes(data)
	if err != nil {
		return 0, err
	}

	for _, n := range notes {
		if n.Provider != provider || n.Probe != probe {
			continue
		}

		for _, prog := range f.Progs {
			if prog.Type != elf.PT_LOAD || (prog.Flags&elf.PF_X) == 0 {
				continue
			}
			if n.Location >= prog.Vaddr && n.Location < prog.Vaddr+prog.Memsz {
				return n.Location - prog.Vaddr + prog.Off, nil
			}
		}

		return 0, fmt.Errorf("probe %s:%s: location %#x not in any PT_LOAD segment", provider, probe, n.Location)
	}

	return 0, fmt.Errorf("probe %s:%s not found in %s", provider, probe, f)
}

func main() {
	elfFile, err := elf.Open(targetPath)
	if err != nil {
		log.Fatalf("opening %s: %v", targetPath, err)
	}

	offset, err := usdtOffset(elfFile, provider, probeName)
	elfFile.Close()
	if err != nil {
		log.Fatalf("resolving USDT probe: %v", err)
	}

	objs := codeObjects{}
	if err := loadCodeObjects(&objs, nil); err != nil {
		log.Fatalf("loading objects: %v", err)
	}
	defer objs.Close()

	ex, err := link.OpenExecutable(targetPath)
	if err != nil {
		log.Fatalf("opening executable: %v", err)
	}

	// The symbol name is irrelevant here: passing a non-zero Address makes
	// cilium/ebpf attach directly at that file offset instead of resolving a
	// symbol by name.
	up, err := ex.Uprobe("", objs.UsdtOrderProcessed, &link.UprobeOptions{Address: offset})
	if err != nil {
		log.Fatalf("attaching uprobe: %v", err)
	}
	defer up.Close()

	sigs := make(chan os.Signal, 1)
	signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)

	fmt.Printf("Attached to %s:%s at offset %#x. Run %s in another terminal.\n", provider, probeName, offset, targetPath)
	<-sigs
	fmt.Println("Exiting...")
}
