#include "vmlinux.h"

#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>

/**
vmlinux.h is autogenerated. Run the following comand in your machine if you want
to use it:

    bpftool btf dump file /sys/kernel/btf/vmlinux format c > sra-monitor_ebpf/bpf/vmlinux.h
*/

SEC("kretprobe/sys_open")
int kretprobe_sys_open(struct pt_regs *ctx) {
    // Extract file path, access type, user ID, timestamp, etc.
    // Store the captured data in eBPF maps.
    return 0;
}

SEC("kretprobe/sys_read")
int kretrobe_sys_read(struct pt_regs *ctx) {
    // Extract relevant information and store in eBPF maps.
    return 0;
}

SEC("kprobe/sys_write")
int kprobe_sys_write(struct pt_regs *ctx) {
    // Extract relevant information and store in eBPF maps.
    return 0;
}

SEC("kprobe/sys_rename")
int kprobe_sys_rename(struct pt_regs *ctx) {
    // Extract relevant information and process it
    return 0;
}

SEC("kprobe/sys_unlink")
int kprobe_sys_unlink(struct pt_regs *ctx) {
    // Extract relevant information and process it
    return 0;
}

char _license[] SEC("license") = "GPL";