/**
vmlinux.h is autogenerated. Run the following comand in your machine if you want
to use it:

    bpftool btf dump file /sys/kernel/btf/vmlinux format c > sra-monitor_ebpf/bpf/vmlinux.h

What's vmlinux.h for?
The command generates a vmlinux.h header file with all kernel types (BTF types) that the running kernel uses.
Including vmlinux.h in your BPF program eliminates dependency on system-wide kernel headers.

For more information refer to this page:
https://docs.kernel.org/bpf/libbpf/libbpf_overview.html
*/
#include "vmlinux.h"

#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>

#define LEN_FILENAME 64
#define LEN_COMM 16

#define MAX_ENTRIES 1024

// Macro that allows to obtain the PID
#define GETPID(x) x >> 32

// Struct containing all relevant information about the syscall event
struct read_event_data {
    char syscall;
    u32 pid;
    u32 uid;
    char comm[LEN_COMM];
    char file[LEN_FILENAME];
    u64 ts_enter;
    u64 ts_exit;
    s32 ret;
};

// Perf map to store events (data_enter/data_exit)
struct {
    __uint(type, BPF_MAP_TYPE_PERF_EVENT_ARRAY);
    __uint(max_entries, MAX_ENTRIES);
    __type(key, u32);
    __type(value, u32);
} file_event_map SEC(".maps");

// Temporary event storage
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, MAX_ENTRIES);
    __type(key, u64);
    __type(value, struct openat_event_data);
} temp_mem SEC(".maps");

// Entry arguments. 
// Documentation in /sys/kernel/tracing/events/syscalls/sys_enter_read
//TODO
struct entry_args_t {
    char _padding1[24];

    const char* filename;
    int flags;
    umode_t mode;
};

// Exit arguments. 
// Documentation in /sys/kernel/tracing/events/syscalls/sys_exit_read
//TODO
struct exit_args_t {
    char _padding1[16];

    s64 ret;
};

SEC("tracepoint/syscalls/sys_enter_read")
int trace_enter_read(struct entry_args_t *ctx) {
        struct read_event_data dat = {};
    u32 key = 0;
    int ret = 0;

    // Add a char to identify the syscall name on the userspace
    dat.syscall = 'r';

    // Extract PID, UID and timestamp
    dat.pid = GETPID(bpf_get_current_pid_tgid());
    dat.uid = bpf_get_current_uid_gid();
    dat.ts_enter = bpf_ktime_get_ns();

    // Get the process that called the sys_open syscall
    bpf_get_current_comm(&dat.comm, LEN_COMM);

    // Get the filename that was accessed
    ret = bpf_probe_read_user_str(&dat.file, LEN_FILENAME, ctx->filename);

    // Output contents to perfmap
    ret = bpf_perf_event_output(ctx, &file_event_map, BPF_F_CURRENT_CPU, &dat, sizeof(dat));

    return 0;
}

SEC("tracepoint/syscalls/sys_exit_read")
int trace_exit_read(struct exit_args_t *ctx){
    struct read_event_data dat= {};

    // Add a char to identify the syscall name on the userspace
    dat.syscall = 'o';

    // Extract PID, UID and timestamp
    dat.pid = GETPID(bpf_get_current_pid_tgid());
    dat.uid = bpf_get_current_uid_gid();
    dat.ts_exit = bpf_ktime_get_ns();

    // Get the process that called the sys_open syscall
    bpf_get_current_comm(&dat.comm, sizeof(dat.comm));

    // Extract the return value form *ctx
    dat.ret = ctx->ret;

    // Output contents to perfmap
    bpf_perf_event_output(ctx, &file_event_map, BPF_F_CURRENT_CPU, &dat, sizeof(dat));
    
    return 0;
}
