/**
vmlinux.h is autogenerated. Run the following comand in your machine if you want
to use it:

    bpftool btf dump file /sys/kernel/btf/vmlinux format c > sra-monitor_ebpf/bpf/vmlinux.h

What's vmlinux.h for?
The command generates a vmlinux.h header file with all kernel types (BTF types) that the running kernel uses.
Including vmlinux.h in your BPF program eliminates dependency on system-wide kernel headers.

For more information refer to this page:
https://docs.kernel.org/bpf/libbpf/libbpf_overview.html
*/
#include "vmlinux.h"

#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>


#define MAX_ENTRIES 1024

// A key-value store is a BPF_MAP_TYPE_HASH, not a BPF_MAP_TYPE_PERF_EVENT_ARRAY:
// the latter is only meant to carry file descriptors for bpf_perf_event_output(),
// which this program never calls.
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, MAX_ENTRIES);
    __type(key, u32);           // type u32 defined in vmlinux.h
    __type(value, umode_t);     // type umode_t defined in vmlinux.h
} file_event_map SEC(".maps");

struct entry_args_t {
    char _padding1[24];

    const char* filename;
    int flags;
    umode_t mode;
};

SEC("tracepoint/syscalls/sys_enter_openat")
int trace_enter_open(struct entry_args_t *ctx) {

    // We assume this map stores the mode associated with each openat flags value seen so far
    u32 key = ctx->flags;
    umode_t* mode = bpf_map_lookup_elem(&file_event_map, &key);
    if (mode == NULL) {
        // First time we see this combination of flags: register it in the map
        umode_t initial_mode = ctx->mode;
        int err = bpf_map_update_elem(&file_event_map, &key, &initial_mode, BPF_NOEXIST);
        if (err < 0) {
            bpf_printk("Error registering flags %d in the map\n", key);
            return -1;
        }
        bpf_printk("New flags value: %d (mode %d)\n", key, initial_mode);
        return 0;
    }

    // We already saw these flags before: update the stored mode to the latest one
    // this is just an example and performs no real action
    *mode = ctx->mode;
    int err = bpf_map_update_elem(&file_event_map, &key, mode, BPF_ANY);
    if (err < 0) {
        bpf_printk("Error updating file descriptor\n");
        return -1;
    }
    bpf_printk("Updated flags %d with mode %d\n", key, *mode);
    return 0;

}
// The license is important, don't forget to put it
char _license[] SEC("license") = "GPL";

