/**
vmlinux.h is autogenerated. Run the following comand in your machine if you want
to use it:

    bpftool btf dump file /sys/kernel/btf/vmlinux format c > sra-monitor_ebpf/bpf/vmlinux.h

What's vmlinux.h for?
The command generates a vmlinux.h header file with all kernel types (BTF types) that the running kernel uses.
Including vmlinux.h in your BPF program eliminates dependency on system-wide kernel headers.

For more information refer to this page:
https://docs.kernel.org/bpf/libbpf/libbpf_overview.html
*/
#include "vmlinux.h"

#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>


#define MAX_ENTRIES 1024

struct {
    __uint(type, BPF_MAP_TYPE_PERF_EVENT_ARRAY);
    __uint(max_entries, MAX_ENTRIES);
    __type(key, u32);           // type u32 defined in vmlinux.h
    __type(value, umode_t);     // type umode_t defined in vmlinux.h
} file_event_map SEC(".maps");

struct entry_args_t {
    char _padding1[24];

    const char* filename;
    int flags;
    umode_t mode;
};

SEC("tracepoint/syscalls/sys_enter_execv")
int trace_enter_execv(struct entry_args_t *ctx) {

    // Get the file descriptor from the map
    // We assume this map stores the flags for the openat syscall
    u64 current_task = bpf_get_current_pid_tgid();

    int pid = current_task;                    
    int tgid = current_task << 32;

    bpf_printk("PID: %d, TGID: %d\n", pid, tgid);
    return 0;
}
// The license is important, don't forget to put it
char _license[] SEC("license") = "GPL";

